//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTI.Modules.ProductCenter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTI.Modules.ProductCenter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acti&amp;vate.
        /// </summary>
        internal static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Product.
        /// </summary>
        internal static string ActivateProductTitle {
            get {
                return ResourceManager.GetString("ActivateProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Product.
        /// </summary>
        internal static string AddProductTitle {
            get {
                return ResourceManager.GetString("AddProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (All).
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowDown {
            get {
                object obj = ResourceManager.GetObject("ArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowUp {
            get {
                object obj = ResourceManager.GetObject("ArrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BG00 {
            get {
                object obj = ResourceManager.GetObject("BG00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BG01 {
            get {
                object obj = ResourceManager.GetObject("BG01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BG02 {
            get {
                object obj = ResourceManager.GetObject("BG02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlackFlatButtonDown {
            get {
                object obj = ResourceManager.GetObject("BlackFlatButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlackFlatButtonUp {
            get {
                object obj = ResourceManager.GetObject("BlackFlatButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlackGelButtonDown {
            get {
                object obj = ResourceManager.GetObject("BlackGelButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlackGelButtonUp {
            get {
                object obj = ResourceManager.GetObject("BlackGelButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlueButtonDown {
            get {
                object obj = ResourceManager.GetObject("BlueButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlueButtonUp {
            get {
                object obj = ResourceManager.GetObject("BlueButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlueFlatButtonDown {
            get {
                object obj = ResourceManager.GetObject("BlueFlatButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlueFlatButtonUp {
            get {
                object obj = ResourceManager.GetObject("BlueFlatButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlueGelButtonDown {
            get {
                object obj = ResourceManager.GetObject("BlueGelButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlueGelButtonUp {
            get {
                object obj = ResourceManager.GetObject("BlueGelButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BookButtonDown {
            get {
                object obj = ResourceManager.GetObject("BookButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BookButtonUp {
            get {
                object obj = ResourceManager.GetObject("BookButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BrownButtonDown {
            get {
                object obj = ResourceManager.GetObject("BrownButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BrownButtonUp {
            get {
                object obj = ResourceManager.GetObject("BrownButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BrownFlatButtonDown {
            get {
                object obj = ResourceManager.GetObject("BrownFlatButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BrownFlatButtonUp {
            get {
                object obj = ResourceManager.GetObject("BrownFlatButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BrownGelButtonDown {
            get {
                object obj = ResourceManager.GetObject("BrownGelButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BrownGelButtonUp {
            get {
                object obj = ResourceManager.GetObject("BrownGelButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to display add product form:.
        /// </summary>
        internal static string ButtonDetailAddProductError {
            get {
                return ResourceManager.GetString("ButtonDetailAddProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button detail error.
        /// </summary>
        internal static string ButtonDetailErrorTitle {
            get {
                return ResourceManager.GetString("ButtonDetailErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have at least one card level.
        /// </summary>
        internal static string CannotDelete {
            get {
                return ResourceManager.GetString("CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save Card Level [{0}].  Changes were not saved..
        /// </summary>
        internal static string CardLevelInUse {
            get {
                return ResourceManager.GetString("CardLevelInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConcessionButtonDown {
            get {
                object obj = ResourceManager.GetObject("ConcessionButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConcessionButtonUp {
            get {
                object obj = ResourceManager.GetObject("ConcessionButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to activate the selected item?.
        /// </summary>
        internal static string ConfirmActivate {
            get {
                return ResourceManager.GetString("ConfirmActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit the application?.
        /// </summary>
        internal static string ConfirmApplicationExit {
            get {
                return ResourceManager.GetString("ConfirmApplicationExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to deactivate the selected item?.
        /// </summary>
        internal static string ConfirmDeactivation {
            get {
                return ResourceManager.GetString("ConfirmDeactivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected item?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected item?.
        /// </summary>
        internal static string ConfirmDeletePackage {
            get {
                return ResourceManager.GetString("ConfirmDeletePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will delete all the buttons, are you sure you want to delete this page?.
        /// </summary>
        internal static string ConfirmDeletePage {
            get {
                return ResourceManager.GetString("ConfirmDeletePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed:
        ///Removes a fixed amount from the sale
        ///Percent Value:
        ///Removes a set percentage of the selected package from the sale
        ///Alt Price:
        ///Uses the &apos;alternative price&apos; value for the products within the package.
        /// </summary>
        internal static string CouponTypeHelpText {
            get {
                return ResourceManager.GetString("CouponTypeHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CreditButtonDown {
            get {
                object obj = ResourceManager.GetObject("CreditButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CreditButtonUp {
            get {
                object obj = ResourceManager.GetObject("CreditButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deacti&amp;vate.
        /// </summary>
        internal static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate Product.
        /// </summary>
        internal static string DeactivateProductTitle {
            get {
                return ResourceManager.GetString("DeactivateProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Discount.
        /// </summary>
        internal static string DeleteDiscountsTitle {
            get {
                return ResourceManager.GetString("DeleteDiscountsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete Card Level [{0}]. Changes were not saved..
        /// </summary>
        internal static string DeleteInUseCardLevel {
            get {
                return ResourceManager.GetString("DeleteInUseCardLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Levels.
        /// </summary>
        internal static string DeleteLevelsTitle {
            get {
                return ResourceManager.GetString("DeleteLevelsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Menu.
        /// </summary>
        internal static string DeleteMenuTitle {
            get {
                return ResourceManager.GetString("DeleteMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Package.
        /// </summary>
        internal static string DeletePackageTitle {
            get {
                return ResourceManager.GetString("DeletePackageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Page.
        /// </summary>
        internal static string DeletePageTitle {
            get {
                return ResourceManager.GetString("DeletePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Product.
        /// </summary>
        internal static string DeleteProductTitle {
            get {
                return ResourceManager.GetString("DeleteProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DiscountButtonDown {
            get {
                object obj = ResourceManager.GetObject("DiscountButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DiscountButtonUp {
            get {
                object obj = ResourceManager.GetObject("DiscountButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform operation, the product is already in the package..
        /// </summary>
        internal static string DuplicatedProduct {
            get {
                return ResourceManager.GetString("DuplicatedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ElectronicButtonDown {
            get {
                object obj = ResourceManager.GetObject("ElectronicButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ElectronicButtonUp {
            get {
                object obj = ResourceManager.GetObject("ElectronicButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Product Group Name.
        /// </summary>
        internal static string EnterProductGroupName {
            get {
                return ResourceManager.GetString("EnterProductGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered by progressive: {0} product type: {1}.
        /// </summary>
        internal static string FilteredByAccrualProductType {
            get {
                return ResourceManager.GetString("FilteredByAccrualProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered by: Package name {0}.
        /// </summary>
        internal static string FilteredByPackageName {
            get {
                return ResourceManager.GetString("FilteredByPackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered by product name: {0} progressive: {1} product type: {2}.
        /// </summary>
        internal static string FilteredByProductNameAccrualProductType {
            get {
                return ResourceManager.GetString("FilteredByProductNameAccrualProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered by product name: {0} product type: {1}.
        /// </summary>
        internal static string FilteredByProductNameProductType {
            get {
                return ResourceManager.GetString("FilteredByProductNameProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered by product type: {0}.
        /// </summary>
        internal static string FilteredByProductType {
            get {
                return ResourceManager.GetString("FilteredByProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Products.
        /// </summary>
        internal static string FilterProducts {
            get {
                return ResourceManager.GetString("FilterProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the device and/or machine id.  Reason: {0}.
        /// </summary>
        internal static string GetDeviceInfoFailed {
            get {
                return ResourceManager.GetString("GetDeviceInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Operator Id.
        /// </summary>
        internal static string GetOperatorIDTitle {
            get {
                return ResourceManager.GetString("GetOperatorIDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Packages.
        /// </summary>
        internal static string GetPackagesTitle {
            get {
                return ResourceManager.GetString("GetPackagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get this workstation&apos;s information from the server.  Reason: {0}.
        /// </summary>
        internal static string GetSettingsFailed {
            get {
                return ResourceManager.GetString("GetSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Settings.
        /// </summary>
        internal static string GetSettingsTitle {
            get {
                return ResourceManager.GetString("GetSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GoldFlatButtonDown {
            get {
                object obj = ResourceManager.GetObject("GoldFlatButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GoldFlatButtonUp {
            get {
                object obj = ResourceManager.GetObject("GoldFlatButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GoldGelButtonDown {
            get {
                object obj = ResourceManager.GetObject("GoldGelButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GoldGelButtonUp {
            get {
                object obj = ResourceManager.GetObject("GoldGelButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GradientFull {
            get {
                object obj = ResourceManager.GetObject("GradientFull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GrayButtonDown {
            get {
                object obj = ResourceManager.GetObject("GrayButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GrayButtonUp {
            get {
                object obj = ResourceManager.GetObject("GrayButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GrayFlatButtonDown {
            get {
                object obj = ResourceManager.GetObject("GrayFlatButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GrayFlatButtonUp {
            get {
                object obj = ResourceManager.GetObject("GrayFlatButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GrayGelButtonDown {
            get {
                object obj = ResourceManager.GetObject("GrayGelButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GrayGelButtonUp {
            get {
                object obj = ResourceManager.GetObject("GrayGelButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreenButtonDown {
            get {
                object obj = ResourceManager.GetObject("GreenButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreenButtonUp {
            get {
                object obj = ResourceManager.GetObject("GreenButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreenFlatButtonDown {
            get {
                object obj = ResourceManager.GetObject("GreenFlatButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreenFlatButtonUp {
            get {
                object obj = ResourceManager.GetObject("GreenFlatButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreenGelButtonDown {
            get {
                object obj = ResourceManager.GetObject("GreenGelButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreenGelButtonUp {
            get {
                object obj = ResourceManager.GetObject("GreenGelButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package already has an open credit product type, only one is allowed..
        /// </summary>
        internal static string HasOpenCredit {
            get {
                return ResourceManager.GetString("HasOpenCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide &amp;Inactive.
        /// </summary>
        internal static string HideInactive {
            get {
                return ResourceManager.GetString("HideInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid game category..
        /// </summary>
        internal static string InvalidGameCategory {
            get {
                return ResourceManager.GetString("InvalidGameCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} response received from server..
        /// </summary>
        internal static string InvalidMessageResponse {
            get {
                return ResourceManager.GetString("InvalidMessageResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Count Error: The Card Count number should be a valid multiple of the On Game..
        /// </summary>
        internal static string InvalidMultipleNumber {
            get {
                return ResourceManager.GetString("InvalidMultipleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid product group..
        /// </summary>
        internal static string InvalidProductGroup {
            get {
                return ResourceManager.GetString("InvalidProductGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid product name..
        /// </summary>
        internal static string InvalidProductName {
            get {
                return ResourceManager.GetString("InvalidProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid product type..
        /// </summary>
        internal static string InvalidProductType {
            get {
                return ResourceManager.GetString("InvalidProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid sales source..
        /// </summary>
        internal static string InvalidSalesSource {
            get {
                return ResourceManager.GetString("InvalidSalesSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LavenderFlatButtonDown {
            get {
                object obj = ResourceManager.GetObject("LavenderFlatButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LavenderFlatButtonUp {
            get {
                object obj = ResourceManager.GetObject("LavenderFlatButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LavenderGelButtonDown {
            get {
                object obj = ResourceManager.GetObject("LavenderGelButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LavenderGelButtonUp {
            get {
                object obj = ResourceManager.GetObject("LavenderGelButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving this workstation&apos;s information..
        /// </summary>
        internal static string LoadingWorkstationInfo {
            get {
                return ResourceManager.GetString("LoadingWorkstationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the log. Reason: {0}.
        /// </summary>
        internal static string LogFailed {
            get {
                return ResourceManager.GetString("LogFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize Logging.
        /// </summary>
        internal static string LogFailedTitle {
            get {
                return ResourceManager.GetString("LogFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MerchandiseButtonDown {
            get {
                object obj = ResourceManager.GetObject("MerchandiseButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MerchandiseButtonUp {
            get {
                object obj = ResourceManager.GetObject("MerchandiseButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} message payload is the wrong size..
        /// </summary>
        internal static string MessagePayloadWrongSize {
            get {
                return ResourceManager.GetString("MessagePayloadWrongSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add a package prior to adding a menu..
        /// </summary>
        internal static string NoPackagesFound {
            get {
                return ResourceManager.GetString("NoPackagesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Products found..
        /// </summary>
        internal static string NoProductsFound {
            get {
                return ResourceManager.GetString("NoProductsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OrangeButtonDown {
            get {
                object obj = ResourceManager.GetObject("OrangeButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OrangeButtonUp {
            get {
                object obj = ResourceManager.GetObject("OrangeButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OrangeFlatButtonDown {
            get {
                object obj = ResourceManager.GetObject("OrangeFlatButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OrangeFlatButtonUp {
            get {
                object obj = ResourceManager.GetObject("OrangeFlatButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OrangeGelButtonDown {
            get {
                object obj = ResourceManager.GetObject("OrangeGelButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OrangeGelButtonUp {
            get {
                object obj = ResourceManager.GetObject("OrangeGelButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OrchidFlatButtonDown {
            get {
                object obj = ResourceManager.GetObject("OrchidFlatButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OrchidFlatButtonUp {
            get {
                object obj = ResourceManager.GetObject("OrchidFlatButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OrchidGelButtonDown {
            get {
                object obj = ResourceManager.GetObject("OrchidGelButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OrchidGelButtonUp {
            get {
                object obj = ResourceManager.GetObject("OrchidGelButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Search.
        /// </summary>
        internal static string PackageSearch {
            get {
                return ResourceManager.GetString("PackageSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PaperBrownButtonDown {
            get {
                object obj = ResourceManager.GetObject("PaperBrownButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PaperBrownButtonUp {
            get {
                object obj = ResourceManager.GetObject("PaperBrownButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PaperButtonDown {
            get {
                object obj = ResourceManager.GetObject("PaperButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PaperButtonUp {
            get {
                object obj = ResourceManager.GetObject("PaperButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PaperGreenButtonDown {
            get {
                object obj = ResourceManager.GetObject("PaperGreenButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PaperGreenButtonUp {
            get {
                object obj = ResourceManager.GetObject("PaperGreenButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PaperOrangeButtonDown {
            get {
                object obj = ResourceManager.GetObject("PaperOrangeButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PaperOrangeButtonUp {
            get {
                object obj = ResourceManager.GetObject("PaperOrangeButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PaperPurpleButtonDown {
            get {
                object obj = ResourceManager.GetObject("PaperPurpleButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PaperPurpleButtonUp {
            get {
                object obj = ResourceManager.GetObject("PaperPurpleButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PaperRainbowButtonDown {
            get {
                object obj = ResourceManager.GetObject("PaperRainbowButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PaperRainbowButtonUp {
            get {
                object obj = ResourceManager.GetObject("PaperRainbowButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PaperRedButtonDown {
            get {
                object obj = ResourceManager.GetObject("PaperRedButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PaperRedButtonUp {
            get {
                object obj = ResourceManager.GetObject("PaperRedButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PaperTanButtonDown {
            get {
                object obj = ResourceManager.GetObject("PaperTanButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PaperTanButtonUp {
            get {
                object obj = ResourceManager.GetObject("PaperTanButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PaperWhiteButtonDown {
            get {
                object obj = ResourceManager.GetObject("PaperWhiteButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PaperWhiteButtonUp {
            get {
                object obj = ResourceManager.GetObject("PaperWhiteButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PinkFlatButtonDown {
            get {
                object obj = ResourceManager.GetObject("PinkFlatButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PinkFlatButtonUp {
            get {
                object obj = ResourceManager.GetObject("PinkFlatButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PinkGelButtonDown {
            get {
                object obj = ResourceManager.GetObject("PinkGelButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PinkGelButtonUp {
            get {
                object obj = ResourceManager.GetObject("PinkGelButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PleaseWait {
            get {
                object obj = ResourceManager.GetObject("PleaseWait", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Center.
        /// </summary>
        internal static string ProductCenterName {
            get {
                return ResourceManager.GetString("ProductCenterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Group.
        /// </summary>
        internal static string ProductGroup {
            get {
                return ResourceManager.GetString("ProductGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Group already exists..
        /// </summary>
        internal static string ProductGroupExists {
            get {
                return ResourceManager.GetString("ProductGroupExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Group [{0}] is currently being used. Changes were not saved..
        /// </summary>
        internal static string ProductGroupInUse {
            get {
                return ResourceManager.GetString("ProductGroupInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None).
        /// </summary>
        internal static string ProductGroupNone {
            get {
                return ResourceManager.GetString("ProductGroupNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product type error.
        /// </summary>
        internal static string ProductTypeErrorTitle {
            get {
                return ResourceManager.GetString("ProductTypeErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected product type is not currently being supported..
        /// </summary>
        internal static string ProductTypeNotSupported {
            get {
                return ResourceManager.GetString("ProductTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PurpleButtonDown {
            get {
                object obj = ResourceManager.GetObject("PurpleButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PurpleButtonUp {
            get {
                object obj = ResourceManager.GetObject("PurpleButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RainbowButtonDown {
            get {
                object obj = ResourceManager.GetObject("RainbowButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RainbowButtonUp {
            get {
                object obj = ResourceManager.GetObject("RainbowButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RainbowFlatButtonDown {
            get {
                object obj = ResourceManager.GetObject("RainbowFlatButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RainbowFlatButtonUp {
            get {
                object obj = ResourceManager.GetObject("RainbowFlatButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RainbowGelButtonDown {
            get {
                object obj = ResourceManager.GetObject("RainbowGelButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RainbowGelButtonUp {
            get {
                object obj = ResourceManager.GetObject("RainbowGelButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RedButtonDown {
            get {
                object obj = ResourceManager.GetObject("RedButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RedButtonUp {
            get {
                object obj = ResourceManager.GetObject("RedButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RedFlatButtonDown {
            get {
                object obj = ResourceManager.GetObject("RedFlatButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RedFlatButtonUp {
            get {
                object obj = ResourceManager.GetObject("RedFlatButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RedGelButtonDown {
            get {
                object obj = ResourceManager.GetObject("RedGelButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RedGelButtonUp {
            get {
                object obj = ResourceManager.GetObject("RedGelButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save product item.
        /// </summary>
        internal static string SaveProductItem {
            get {
                return ResourceManager.GetString("SaveProductItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server communication lost..
        /// </summary>
        internal static string ServerCommFailed {
            get {
                return ResourceManager.GetString("ServerCommFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server returned error code: {0}.
        /// </summary>
        internal static string ServerErrorCode {
            get {
                return ResourceManager.GetString("ServerErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SetButtonDown {
            get {
                object obj = ResourceManager.GetObject("SetButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SetButtonUp {
            get {
                object obj = ResourceManager.GetObject("SetButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;Inactive.
        /// </summary>
        internal static string ShowInactive {
            get {
                return ResourceManager.GetString("ShowInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Product Center..
        /// </summary>
        internal static string StartingProductCenter {
            get {
                return ResourceManager.GetString("StartingProductCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TanFlatButtonDown {
            get {
                object obj = ResourceManager.GetObject("TanFlatButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TanFlatButtonUp {
            get {
                object obj = ResourceManager.GetObject("TanFlatButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TanGelButtonDown {
            get {
                object obj = ResourceManager.GetObject("TanGelButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TanGelButtonUp {
            get {
                object obj = ResourceManager.GetObject("TanGelButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Multiples.
        /// </summary>
        internal static string ValidateMultiplesTitle {
            get {
                return ResourceManager.GetString("ValidateMultiplesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhiteButtonDown {
            get {
                object obj = ResourceManager.GetObject("WhiteButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhiteButtonUp {
            get {
                object obj = ResourceManager.GetObject("WhiteButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhiteFlatButtonDown {
            get {
                object obj = ResourceManager.GetObject("WhiteFlatButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhiteFlatButtonUp {
            get {
                object obj = ResourceManager.GetObject("WhiteFlatButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhiteGelButtonDown {
            get {
                object obj = ResourceManager.GetObject("WhiteGelButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhiteGelButtonUp {
            get {
                object obj = ResourceManager.GetObject("WhiteGelButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YellowButtonDown {
            get {
                object obj = ResourceManager.GetObject("YellowButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YellowButtonUp {
            get {
                object obj = ResourceManager.GetObject("YellowButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YellowFlatButtonDown {
            get {
                object obj = ResourceManager.GetObject("YellowFlatButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YellowFlatButtonUp {
            get {
                object obj = ResourceManager.GetObject("YellowFlatButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YellowGelButtonDown {
            get {
                object obj = ResourceManager.GetObject("YellowGelButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YellowGelButtonUp {
            get {
                object obj = ResourceManager.GetObject("YellowGelButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
